#include "MazeGenerator.h"
#include <vector>
#include <cstdio>
#include <cstdlib>
#include <ctime>

MazeGenerator::Point MazeGenerator::getRandomEdgePoint(int n)
{
    MazeGenerator::Point p;
    int edge = rand() % 4; // 0: up, 1: down, 2: left, 3: right

    int rand_pos = 1 + 2 * (rand() % ((n - 1) / 2));

    switch (edge)
    {
    case 0: // up
        p.edge_x = rand_pos;
        p.edge_y = 0;
        p.in_x = rand_pos;
        p.in_y = 1;
        break;
    case 1: // down
        p.edge_x = rand_pos;
        p.edge_y = n - 1;
        p.in_x = rand_pos;
        p.in_y = n - 2;
        break;
    case 2: // left
        p.edge_x = 0;
        p.edge_y = rand_pos;
        p.in_x = 1;
        p.in_y = rand_pos;
        break;
    case 3: // right
        p.edge_x = n - 1;
        p.edge_y = rand_pos;
        p.in_x = n - 2;
        p.in_y = rand_pos;
        break;
    default:
        // error
        break;
    }
    return p;
}







// shuffle function to randomize the directions
void MazeGenerator::shuffle(int *array, int n)
{
    for (int i = 0; i < n - 1; i++)
    {
        int j = i + rand() / (RAND_MAX / (n - i) + 1);
        int t = array[j];
        array[j] = array[i];
        array[i] = t;
    }
}







// generate maze paths using recursive backtracking DFS algorithm 
// entrance and exit are not generated by this function, they are handled separately in generateMaze function
void MazeGenerator::generatePaths(std::vector<std::vector<int>> &matrix, int x, int y, int n)
{
    int dirs[] = {0, 1, 2, 3}; // 0:Up, 1:Down, 2:Left, 3:Right
    shuffle(dirs, 4);

    for (int i = 0; i < 4; i++)
    {
        int dx = 0, dy = 0;
        if (dirs[i] == 0) // Up
        {
            dy = -2;
        }
        else if (dirs[i] == 1) // Down
        {
            dy = 2;
        }
        else if (dirs[i] == 2) // Left
        {
            dx = -2;
        }
        else if (dirs[i] == 3) // Right
        {
            dx = 2;
        }

        int nx = x + dx;
        int ny = y + dy;

        if (nx >= 0 && nx < n && ny >= 0 && ny < n && matrix[ny][nx] == WALL)
        {
            matrix[y + dy / 2][x + dx / 2] = PATH; // Remove wall
            matrix[ny][nx] = PATH;
            generatePaths(matrix, nx, ny, n);
        }
    }
}






//  main function to generate maze with an entrance and exit and save it to file
void MazeGenerator::generateMaze(int n, const char *filename)
{
    MazeManager manager;
    // Initialize maze matrix
    std::vector<std::vector<int>> matrix(n, std::vector<int>(n, WALL));
    matrix.assign(n, std::vector<int>(n, WALL));

    MazeGenerator::Point start = getRandomEdgePoint(n);
    MazeGenerator::Point end;
    do
    {
        end = getRandomEdgePoint(n);
    } while (start.edge_x == end.edge_x && start.edge_y == end.edge_y); // Ensure start and end are different

    // Open the entrance 
    matrix[start.in_y][start.in_x] = PATH; 
    // Generate the maze paths
    generatePaths(matrix, start.in_x, start.in_y, n);
    
    // Open the exit
    matrix[start.edge_y][start.edge_x] = PATH;
    matrix[end.edge_y][end.edge_x] = PATH;
    matrix[end.in_y][end.in_x] = PATH;

    manager.saveMazeToFile(matrix, n, start.edge_x, start.edge_y, end.edge_x, end.edge_y, filename);

    // Clean up
    matrix.clear();
}

