#include "MazeGenerator.h"


Point getRandomEdgePoint(int n)
{
    Point p;
    int edge = rand() % 4; // 0: up, 1: down, 2: left, 3: right

    int rand_pos = 1 + 2 * (rand() % ((n - 1) / 2));

    switch (edge)
    {
    case 0: // up
        p.edge_x = rand_pos;
        p.edge_y = 0;
        p.in_x = rand_pos;
        p.in_y = 1;
        break;
    case 1: // down
        p.edge_x = rand_pos;
        p.edge_y = n - 1;
        p.in_x = rand_pos;
        p.in_y = n - 2;
        break;
    case 2: // left
        p.edge_x = 0;
        p.edge_y = rand_pos;
        p.in_x = 1;
        p.in_y = rand_pos;
        break;
    case 3: // right
        p.edge_x = n - 1;
        p.edge_y = rand_pos;
        p.in_x = n - 2;
        p.in_y = rand_pos;
        break;
    default:
        // error
        break;
    }
    return p;
}

// shuffle function to randomize the directions
void shuffle(int *array, int n)
{
    for (int i = 0; i < n - 1; i++)
    {
        int j = i + rand() / (RAND_MAX / (n - i) + 1);
        int t = array[j];
        array[j] = array[i];
        array[i] = t;
    }
}


// generate maze paths using recursive backtracking DFS algorithm 
// entrance and exit are not generated by this function, they are handled separately in generateMaze function
void generatePaths(int **matrix, int x, int y, int n)
{
    int dirs[] = {0, 1, 2, 3}; // 0:Up, 1:Down, 2:Left, 3:Right
    shuffle(dirs, 4);

    for (int i = 0; i < 4; i++)
    {
        int dx = 0, dy = 0;
        if (dirs[i] == 0) // Up
        {
            dy = -2;
        }
        else if (dirs[i] == 1) // Down
        {
            dy = 2;
        }
        else if (dirs[i] == 2) // Left
        {
            dx = -2;
        }
        else if (dirs[i] == 3) // Right
        {
            dx = 2;
        }

        int nx = x + dx;
        int ny = y + dy;

        if (nx >= 0 && nx < n && ny >= 0 && ny < n && matrix[ny][nx] == WALL)
        {
            matrix[y + dy / 2][x + dx / 2] = PATH; // Remove wall
            matrix[ny][nx] = PATH;
            generatePaths(matrix, nx, ny, n);
        }
    }
}


// save maze to file in the specified format (.txt)
void saveMazeToFile(int **matrix, int n, Point start, Point end, const char *filename)
{
    FILE *file = fopen(filename, "w");
    if (file == nullptr)
    {
        perror("Failed to open file");
        return;
    }

    fprintf(file, "%d %d\n", n, n);                       // Write maze dimensions
    fprintf(file, "%d %d\n", start.edge_x, start.edge_y); // Write start point
    fprintf(file, "%d %d\n", end.edge_x, end.edge_y);     // Write end point

    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n; j++)
        {
            fprintf(file, "%d ", matrix[i][j]);
        }
        fprintf(file, "\n");
    }

    fclose(file);
}


//  main function to generate maze with an entrance and exit and save it to file
void generateMaze(int n, const char *filename)
{
    // Initialize maze matrix
    int **matrix = new int *[n];
    for (int i = 0; i < n; i++)
    {
        matrix[i] = new int[n];
        for (int j = 0; j < n; j++)
        {
            matrix[i][j] = WALL;
        }
    }

    Point start = getRandomEdgePoint(n);
    Point end;
    do
    {
        end = getRandomEdgePoint(n);
    } while (start.edge_x == end.edge_x && start.edge_y == end.edge_y); // Ensure start and end are different

    // Open the entrance 
    matrix[start.in_y][start.in_x] = PATH; 
    // Generate the maze paths
    generatePaths(matrix, start.in_x, start.in_y, n);
    
    // Open the exit
    matrix[start.edge_y][start.edge_x] = PATH;
    matrix[end.edge_y][end.edge_x] = PATH;
    matrix[end.in_y][end.in_x] = PATH;

    saveMazeToFile(matrix, n, start, end, filename);

    // Clean up
    for (int i = 0; i < n; i++)
    {
        delete[] matrix[i];
    }
    delete[] matrix;
}


void getMazeSizeFromFile(const char *filename, int &n) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Failed to open file: " << filename << std::endl;
        return;
    }
    int temp_n;

    if (!(file >> n >> temp_n)) {
        std::cerr << "Failed to read maze size from file: " << filename << std::endl;
        n = -1;
    }

    file.close();
}



void getStartIndicesFromFile(const char *filename, int &start_x, int &start_y) {
    std::ifstream file(filename);
    
    if (!file.is_open()) {
        std::cerr << "Failed to open file: " << filename << std::endl;
        return;
    }

    std::string line;
    std::getline(file, line);

    if (!(file >> start_x >> start_y)) {
        std::cerr << "Failed to read start indices from file: " << filename << std::endl;
        start_x = start_y = -1;
    }

    file.close();
}


void getEndIndicesFromFile(const char *filename, int &end_x, int &end_y) {
    std::ifstream file(filename);
    
    if (!file.is_open()) {
        std::cerr << "Failed to open file: " << filename << std::endl;
        return;
    }

    std::string line;
    std::getline(file, line);
    std::getline(file, line);

    if (!(file >> end_x >> end_y)) {
        std::cerr << "Failed to read end indices from file: " << filename << std::endl;
        end_x = end_y = -1;
    }

    file.close();
}


void getMazeFromFile(const char *filename, int **matrix, int n)
{
    std::ifstream file(filename);
    if (!file.is_open())
    {
        std::cerr << "Error opening file: " << filename << std::endl;
        return;
    }

    std::string line;
    for (int i = 0; i < 3; i++)
    {
        std::getline(file, line);
    }

    for (int i = 0; i < n; ++i)
    {
        for (int j = 0; j < n; ++j)
        {
            if (!(file >> matrix[i][j])) break;
        }
    }
}



void printMaze(const char *filename, int n)
{
    int **matrix = new int *[n];
    for (int i = 0; i < n; i++)
    {
        matrix[i] = new int[n];
    }

    getMazeFromFile(filename, matrix, n);

    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n; j++)
        {
            printf("%s", matrix[i][j] == WALL ? "██" : "  ");
        }
        printf("\n");
    }

    // Clean up
    for (int i = 0; i < n; i++) {
        delete[] matrix[i];
    }
    delete[] matrix;
}



int main(int argc, char *argv[])
{
    if (argc != 3 || atoi(argv[1]) <= 0 || atoi(argv[1]) % 2 == 0)
    {
        fprintf(stderr, "Usage: %s <maze_size> <output_file>\n Maze size must be a positive odd integer.", argv[0]);
        return 1;
    }

    int n = atoi(argv[1]);
    const char *filename = argv[2];
    srand(time(NULL));

    try
    {
        generateMaze(n, filename);
        printMaze(filename, n);
    }
    catch (const std::exception &e)
    {
        std::cerr << "Error: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}
